language: python
install:
  - pip3 install numpy
  - pip3 install scipy 
  - pip3 install matplotlib
  - pip3 install nose
  - git clone https://github.com/jonathf/chaospy.git
  - cd chaospy
  - git checkout development
  - pip3 install .
script:
  - python3 -m nose
