# This workflow will upload a Python Package using Twine when a push is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package to Test PYPI

on:
  push

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      if: startsWith(github.ref, 'refs/tags')
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      if: startsWith(github.ref, 'refs/tags')
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      if: startsWith(github.ref, 'refs/tags')
      run: python -m build
    - name: Publish package to Test PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
